version: '3'

services:
  main:
    build: ./docker
    container_name: comisc-docker-main
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
#    ports:
#      - 8000:8000
#    depends_on:
#      - postgresql
#
#  postgresql:
#    container_name: comisc-docker-postgresql
#    image: postgres:13.1-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    restart: always
#    ports:
#      - 8901:5432
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data